name: Builders-Utilities
version: "${version}"
api-version: 1.13
main: net.arcaniax.buildersutilities.BuildersUtilities
authors: [ Ktar5, Arcaniax ]
website: "https://www.spigotmc.org/resources/42361/"
commands:
  butil:
    aliases: bu
    description: opens toggle menu
  banner:
    description: opens banner creator
    aliases: bm
  armorcolor:
    description: opens armor color creator
    aliases: color
  nc:
    aliases: noclip
    description: Toggles NoClip.
  af:
    aliases: advfly
    description: Toggles Advanced fly.
  n:
    aliases: nv
    description: Toggles Nightvision.
  blocks:
    description: Opens secret blocks menu
    aliases: secretblocks
  help:
    description: Help command

permissions:
  builders.util.trapdoor:
    default: false
  builders.util.slabs:
    default: false
  builders.util.terracotta:
    default: false
  builders.util.nightvision:
    default: false
  builders.util.noclip:
    default: false
  builders.util.advancedfly:
    default: false